chore: remove mssql CI

diff --git a/.github/workflows/ci_assembly.yml b/.github/workflows/ci_assembly.yml
--- a/.github/workflows/ci_assembly.yml
+++ b/.github/workflows/ci_assembly.yml
@@ -14,20 +14,20 @@ jobs:
     runs-on: ubuntu-latest
 
     services:
-      mssql:
-        image: mcr.microsoft.com/mssql/server:2022-CU14-ubuntu-22.04
-        env:
-          ACCEPT_EULA: Y
-          SA_PASSWORD: YourStrong!Passw0rd
-        ports:
-          - 1433:1433
-        options:           
-           --health-interval=10s 
-           --health-interval=20s 
-           --health-timeout=3s 
-           --health-start-period=10s 
-           --health-retries=10 
-           --health-cmd="sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -Q 'SELECT 1' || exit 1"
+      # mssql:
+      #   image: mcr.microsoft.com/mssql/server:2022-CU14-ubuntu-22.04
+      #   env:
+      #     ACCEPT_EULA: Y
+      #     SA_PASSWORD: YourStrong!Passw0rd
+      #   ports:
+      #     - 1433:1433
+      #   options:           
+      #      --health-interval=10s 
+      #      --health-interval=20s 
+      #      --health-timeout=3s 
+      #      --health-start-period=10s 
+      #      --health-retries=10 
+      #      --health-cmd="sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -Q 'SELECT 1' || exit 1"
  
       pgsql:
         image: ghcr.io/openimis/openimis-pgsql:develop
@@ -109,39 +109,39 @@ jobs:
           DB_USER: postgres
           DB_PASSWORD: YourStrong!Passw0rd
 
-      - name: Initialize MSSQL
-        run: |
-          export DB_NAME_TEST="test_$DB_NAME"
+      # - name: Initialize MSSQL
+      #   run: |
+      #     export DB_NAME_TEST="test_$DB_NAME"
           
-          if [ ${GITHUB_REF##*/} = "main" ]; then export DBBRANCH="main"; else export DBBRANCH="develop"; fi
-          echo "Branch ${GITHUB_REF##*/}, usign ${DBBRANCH} branch for database"
-          git clone --depth=1 --branch=$DBBRANCH https://github.com/openimis/database_ms_sqlserver.git ./sql_mssql
-          cd sql_mssql/ && bash concatenate_files.sh && cd ..
+      #     if [ ${GITHUB_REF##*/} = "main" ]; then export DBBRANCH="main"; else export DBBRANCH="develop"; fi
+      #     echo "Branch ${GITHUB_REF##*/}, usign ${DBBRANCH} branch for database"
+      #     git clone --depth=1 --branch=$DBBRANCH https://github.com/openimis/database_ms_sqlserver.git ./sql_mssql
+      #     cd sql_mssql/ && bash concatenate_files.sh && cd ..
 
-          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
-          curl https://packages.microsoft.com/config/ubuntu/24.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
-          sudo apt-get update
-          sudo apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages mssql-tools18 unixodbc-dev
-          echo "Waiting for SQL Server to be fully operational..."
-          until /opt/mssql-tools18/bin/sqlcmd -S localhost -U $DB_USER -P $DB_PASSWORD -Q "SELECT @@VERSION" > /dev/null 2>&1
-          do
-            echo "SQL Server is still initializing. Waiting..."
-            sleep 5
-          done
-          echo "SQL Server is now operational."
-          #Main db has to exists for tests to run correctly, psql container creates empty main db by default
-          /opt/mssql-tools18/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -Q "DROP DATABASE IF EXISTS $DB_NAME"
-          /opt/mssql-tools18/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -Q "CREATE DATABASE $DB_NAME"
+      #     curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
+      #     curl https://packages.microsoft.com/config/ubuntu/24.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
+      #     sudo apt-get update
+      #     sudo apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages mssql-tools18 unixodbc-dev
+      #     echo "Waiting for SQL Server to be fully operational..."
+      #     until /opt/mssql-tools18/bin/sqlcmd -S localhost -U $DB_USER -P $DB_PASSWORD -Q "SELECT @@VERSION" > /dev/null 2>&1
+      #     do
+      #       echo "SQL Server is still initializing. Waiting..."
+      #       sleep 5
+      #     done
+      #     echo "SQL Server is now operational."
+      #     #Main db has to exists for tests to run correctly, psql container creates empty main db by default
+      #     /opt/mssql-tools18/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -Q "DROP DATABASE IF EXISTS $DB_NAME"
+      #     /opt/mssql-tools18/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -Q "CREATE DATABASE $DB_NAME"
 
-          /opt/mssql-tools18/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -Q "DROP DATABASE IF EXISTS $DB_NAME_TEST"
-          /opt/mssql-tools18/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -Q "CREATE DATABASE $DB_NAME_TEST"
-          /opt/mssql-tools18/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -d $DB_NAME_TEST -i ./sql_mssql/output/fullDemoDatabase.sql | grep . | uniq -c
-        env:
-          DB_HOST: localhost
-          DB_PORT: 1433
-          DB_NAME: imis
-          DB_USER: sa
-          DB_PASSWORD: YourStrong!Passw0rd
+      #     /opt/mssql-tools18/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -Q "DROP DATABASE IF EXISTS $DB_NAME_TEST"
+      #     /opt/mssql-tools18/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -Q "CREATE DATABASE $DB_NAME_TEST"
+      #     /opt/mssql-tools18/bin/sqlcmd -S $DB_HOST -U $DB_USER -P $DB_PASSWORD -d $DB_NAME_TEST -i ./sql_mssql/output/fullDemoDatabase.sql | grep . | uniq -c
+      #   env:
+      #     DB_HOST: localhost
+      #     DB_PORT: 1433
+      #     DB_NAME: imis
+      #     DB_USER: sa
+      #     DB_PASSWORD: YourStrong!Passw0rd
 
       - name: Django tests PSQL
         working-directory: ./openIMIS
